// 种子脚本：插入一批示例影片，让「拉下来即可跑」流程可见可点。
// 直接运行：npm run db:seed（内部用 tsx 执行本文件）。
// 说明：示例数据不依赖 TMDb Key，海报留空，前端自动回退 picsum 占位图。
import { getDb } from "../lib/db";
import type { Client } from "@libsql/client";
import type { Item } from "../lib/types";

// 以下两个写库函数仅在本种子脚本内使用，不污染 lib/queries（保持应用层纯只读）。
// 全部使用参数化占位符，杜绝 SQL 注入。

// 写入/更新影片元数据（按 tmdb_id 去重缓存）。
async function ensureItem(db: Client, it: Item): Promise<void> {
  await db.execute({
    sql: `INSERT OR REPLACE INTO imovie_items (
      tmdb_id, media_type, title, original_title, year, poster_path, overview,
      director, writer, cast, genres, country, language, release_date, runtime,
      aka, imdb_id, douban_rating, tmdb_rating
    ) VALUES (
      ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
    )`,
    args: [
      it.tmdb_id,
      it.media_type,
      it.title,
      it.original_title ?? null,
      it.year ?? null,
      it.poster_path ?? null,
      it.overview ?? null,
      it.director ?? null,
      it.writer ?? null,
      it.cast ?? null,
      it.genres ?? null,
      it.country ?? null,
      it.language ?? null,
      it.release_date ?? null,
      it.runtime ?? null,
      it.aka ?? null,
      it.imdb_id ?? null,
      it.douban_rating ?? null,
      it.tmdb_rating ?? null,
    ],
  });
}

// 写入/更新观影记录（同一用户同一影片唯一；评分仅 watched 时带入）。
async function upsertRecord(
  db: Client,
  r: { tmdb_id: number; status: "plan" | "watched"; rating: number | null; tags: string }
): Promise<void> {
  await db.execute({
    sql: `INSERT INTO imovie_records (tmdb_id, user_id, status, rating, tags)
      VALUES (?, 1, ?, ?, ?)
      ON CONFLICT(user_id, tmdb_id) DO UPDATE SET
        status = excluded.status,
        rating = excluded.rating,
        tags = excluded.tags`,
    args: [r.tmdb_id, r.status, r.rating ?? null, r.tags ?? ""],
  });
}

// 示例影片：涵盖电影/剧集、中外、动画、多种类型；部分带站内评分、标签。
// 前 6 部为真实详细数据，其余为经典/知名影片的概览数据（tmdb_id 为测试用合成值）。
const items: Item[] = [
  {
    tmdb_id: 950396,
    media_type: "movie",
    title: "奥本海默",
    original_title: "Oppenheimer",
    year: 2023,
    poster_path: null,
    overview: "二战期间，美国物理学家奥本海默主导曼哈顿计划，研制出原子弹，却也开启核时代的道德困境。",
    director: "克里斯托弗·诺兰",
    writer: "克里斯托弗·诺兰",
    cast: "基里安·墨菲 / 艾米莉·布朗特 / 小罗伯特·唐尼 / 马特·达蒙",
    genres: "剧情 / 历史 / 传记",
    country: "美国 / 英国",
    language: "英语",
    release_date: "2023-08-30(中国大陆)",
    runtime: 180,
    aka: "奥本海默 / 欧本海默",
    imdb_id: "tt15398776",
    tmdb_rating: 8.1,
    douban_rating: 8.3,
  },
  {
    tmdb_id: 872585,
    media_type: "movie",
    title: "银河护卫队3",
    original_title: "Guardians of the Galaxy Vol. 3",
    year: 2023,
    poster_path: null,
    overview: "为了保护火箭浣熊，护卫队踏上一段危机四伏的旅程，直面火箭痛苦的过往。",
    director: "詹姆斯·古恩",
    writer: "詹姆斯·古恩",
    cast: "克里斯·帕拉特 / 佐伊·索尔达娜 / 戴夫·巴蒂斯塔",
    genres: "动作 / 科幻 / 冒险",
    country: "美国",
    language: "英语",
    release_date: "2023-05-05(中国大陆)",
    runtime: 150,
    aka: "银河守护队3 / 星际异攻队3",
    imdb_id: "tt6791350",
    tmdb_rating: 7.9,
    douban_rating: 8.2,
  },
  {
    tmdb_id: 639933,
    media_type: "tv",
    title: "王冠 第六季",
    original_title: "The Crown",
    year: 2023,
    poster_path: null,
    overview: "伊丽莎白二世的统治进入尾声，戴安娜王妃的悲剧与王室如何应对时代变革成为焦点。",
    director: "皮特·摩根",
    writer: "皮特·摩根",
    cast: "艾美达·斯丹顿 / 伊丽莎白·德比茨基 / 多米尼克·韦斯特",
    genres: "剧情 / 传记 / 历史",
    country: "英国",
    language: "英语",
    release_date: "2023-11-16",
    runtime: 50,
    aka: "王冠",
    imdb_id: "tt4786824",
    tmdb_rating: 8.0,
    douban_rating: 8.1,
  },
  {
    tmdb_id: 1127718,
    media_type: "movie",
    title: "可怜的东西",
    original_title: "Poor Things",
    year: 2023,
    poster_path: null,
    overview: "被科学家复活的贝拉踏上自我觉醒之旅，以荒诞视角重新审视自由、欲望与社会规训。",
    director: "欧格斯·兰斯莫斯",
    writer: "托尼·麦克纳马拉",
    cast: "艾玛·斯通 / 马克·鲁法洛 / 威廉·达福",
    genres: "剧情 / 喜剧 / 科幻",
    country: "英国 / 爱尔兰 / 美国",
    language: "英语",
    release_date: "2023-12-08(中国大陆)",
    runtime: 141,
    aka: "可怜的东西 / 乖乖女是大佬",
    imdb_id: "tt14230458",
    tmdb_rating: 7.8,
    douban_rating: 7.3,
  },
  {
    tmdb_id: 100402,
    media_type: "tv",
    title: "繁花",
    original_title: "Blossoms Shanghai",
    year: 2023,
    poster_path: null,
    overview: "上世纪九十年代的上海，阿宝在时代浪潮中创业沉浮，描绘一幅沪上人情世相图。",
    director: "王家卫",
    writer: "王家卫 / 金宇澄",
    cast: "胡歌 / 马伊琍 / 唐嫣 / 辛芷蕾",
    genres: "剧情",
    country: "中国大陆",
    language: "汉语普通话 / 上海话",
    release_date: "2023-12-27(中国大陆)",
    runtime: 45,
    aka: "花繁",
    imdb_id: null,
    tmdb_rating: 8.2,
    douban_rating: 8.6,
  },
  {
    tmdb_id: 693134,
    media_type: "movie",
    title: "坠落",
    original_title: "Fall",
    year: 2022,
    poster_path: null,
    overview: "两名好友攀登荒废高塔，却因绳索断裂被困塔顶，展开惊心动魄的求生。",
    director: "斯科特·曼",
    writer: "斯科特·曼 / 乔纳森·弗兰克",
    cast: "格蕾丝·富尔顿 / 维吉尼亚·加德纳",
    genres: "惊悚 / 冒险",
    country: "美国 / 英国",
    language: "英语",
    release_date: "2022-11-18(中国大陆)",
    runtime: 107,
    aka: "坠落 / 攀上高峰",
    imdb_id: "tt9327408",
    tmdb_rating: 6.7,
    douban_rating: 6.7,
  },

  // ===== 新增经典 / 知名影片（测试数据，tmdb_id 为合成值） =====
  {
    tmdb_id: 2000001,
    media_type: "movie",
    title: "霸王别姬",
    original_title: "Farewell My Concubine",
    year: 1993,
    poster_path: null,
    overview: "程蝶衣与段小楼半个世纪的悲欢，映照时代洪流中戏子与戏、情与命运的纠缠。",
    director: "陈凯歌",
    writer: "芦苇 / 李碧华",
    cast: "张国荣 / 张丰毅 / 巩俐",
    genres: "剧情 / 爱情 / 同性",
    country: "中国大陆 / 香港",
    language: "汉语普通话",
    release_date: "1993-01-01(中国大陆)",
    runtime: 171,
    aka: "再见，我的妾",
    imdb_id: "tt0106332",
    tmdb_rating: 8.1,
    douban_rating: 7.9,
  },
  {
    tmdb_id: 2000002,
    media_type: "movie",
    title: "阿甘正传",
    original_title: "Forrest Gump",
    year: 1994,
    poster_path: null,
    overview: "智商不高却心地纯善的阿甘，用奔跑般的人生见证了美国半个世纪的变迁。",
    director: "罗伯特·泽米吉斯",
    writer: "艾瑞克·罗斯",
    cast: "汤姆·汉克斯 / 罗宾·怀特 / 加里·西尼斯",
    genres: "剧情 / 爱情",
    country: "美国",
    language: "英语",
    release_date: "1994-07-06(美国)",
    runtime: 142,
    aka: "福雷斯特·冈普",
    imdb_id: "tt0109830",
    tmdb_rating: 8.8,
    douban_rating: 9.3,
  },
  {
    tmdb_id: 2000003,
    media_type: "movie",
    title: "泰坦尼克号",
    original_title: "Titanic",
    year: 1997,
    poster_path: null,
    overview: "穷画家杰克与贵族少女露丝在永不沉没的巨轮上相遇相爱，却迎面撞上命运的冰山。",
    director: "詹姆斯·卡梅隆",
    writer: "詹姆斯·卡梅隆",
    cast: "莱昂纳多·迪卡普里奥 / 凯特·温斯莱特 / 比利·赞恩",
    genres: "剧情 / 爱情 / 灾难",
    country: "美国",
    language: "英语",
    release_date: "1998-04-03(中国大陆)",
    runtime: 194,
    aka: "铁达尼号",
    imdb_id: "tt0120338",
    tmdb_rating: 7.9,
    douban_rating: 8.2,
  },
  {
    tmdb_id: 2000004,
    media_type: "movie",
    title: "千与千寻",
    original_title: "千と千尋の神隠し",
    year: 2001,
    poster_path: null,
    overview: "误入神灵世界的少女千寻，为救变成猪的父母在汤屋打工，学会勇敢与成长。",
    director: "宫崎骏",
    writer: "宫崎骏",
    cast: "柊瑠美 / 入野自由 / 夏木真理",
    genres: "动画 / 奇幻 / 冒险",
    country: "日本",
    language: "日语",
    release_date: "2019-06-21(中国大陆)",
    runtime: 125,
    aka: "神隐少女",
    imdb_id: "tt0245429",
    tmdb_rating: 8.6,
    douban_rating: 8.4,
  },
  {
    tmdb_id: 2000005,
    media_type: "movie",
    title: "盗梦空间",
    original_title: "Inception",
    year: 2010,
    poster_path: null,
    overview: "盗梦专家柯布潜入他人梦境窃取秘密，却接下一桩在潜意识中植入想法的不可能的任务。",
    director: "克里斯托弗·诺兰",
    writer: "克里斯托弗·诺兰",
    cast: "莱昂纳多·迪卡普里奥 / 渡边谦 / 玛丽昂·歌迪亚",
    genres: "科幻 / 悬疑 / 冒险",
    country: "美国 / 英国",
    language: "英语",
    release_date: "2010-09-01(中国大陆)",
    runtime: 148,
    aka: "全面启动 / 奠基",
    imdb_id: "tt1375666",
    tmdb_rating: 8.4,
    douban_rating: 8.9,
  },
  {
    tmdb_id: 2000006,
    media_type: "movie",
    title: "星际穿越",
    original_title: "Interstellar",
    year: 2014,
    poster_path: null,
    overview: "地球濒临枯竭，前宇航员库珀穿越虫洞为人类寻找新家园，却要直面时空与亲情的抉择。",
    director: "克里斯托弗·诺兰",
    writer: "克里斯托弗·诺兰 / 乔纳森·诺兰",
    cast: "马修·麦康纳 / 安妮·海瑟薇 / 杰西卡·查斯坦",
    genres: "科幻 / 冒险 / 剧情",
    country: "美国 / 英国",
    language: "英语",
    release_date: "2014-11-12(中国大陆)",
    runtime: 169,
    aka: "星际启示录",
    imdb_id: "tt0816692",
    tmdb_rating: 8.4,
    douban_rating: 8.0,
  },
  {
    tmdb_id: 2000007,
    media_type: "movie",
    title: "教父",
    original_title: "The Godfather",
    year: 1972,
    poster_path: null,
    overview: "纽约黑帮柯里昂家族的权力更替，长子迈克从局外人一步步走向家族王座。",
    director: "弗朗西斯·福特·科波拉",
    writer: "马里奥·普佐 / 弗朗西斯·福特·科波拉",
    cast: "马龙·白兰度 / 阿尔·帕西诺 / 詹姆斯·肯恩",
    genres: "剧情 / 犯罪",
    country: "美国",
    language: "英语 / 意大利语",
    release_date: "1972-03-24(美国)",
    runtime: 175,
    aka: "教父1",
    imdb_id: "tt0068646",
    tmdb_rating: 8.7,
    douban_rating: 8.7,
  },
  {
    tmdb_id: 2000008,
    media_type: "movie",
    title: "这个杀手不太冷",
    original_title: "Léon",
    year: 1994,
    poster_path: null,
    overview: "孤独的职业杀手里昂收留了全家遇害的小女孩玛蒂尔达，两个边缘人彼此取暖。",
    director: "吕克·贝松",
    writer: "吕克·贝松",
    cast: "让·雷诺 / 娜塔莉·波特曼 / 加里·奥德曼",
    genres: "剧情 / 动作 / 犯罪",
    country: "法国",
    language: "英语 / 法语 / 意大利语",
    release_date: "1994-09-14(法国)",
    runtime: 110,
    aka: "杀手莱昂 / 终极追杀令",
    imdb_id: "tt0110413",
    tmdb_rating: 8.5,
    douban_rating: 8.7,
  },
  {
    tmdb_id: 2000009,
    media_type: "movie",
    title: "楚门的世界",
    original_title: "The Truman Show",
    year: 1998,
    poster_path: null,
    overview: "楚门的生活其实是一档被全球围观的真人秀，当他察觉真相后决心逃离虚构的世界。",
    director: "彼得·威尔",
    writer: "安德鲁·尼科尔",
    cast: "金·凯瑞 / 劳拉·琳妮 / 艾德·哈里斯",
    genres: "剧情 / 科幻",
    country: "美国",
    language: "英语",
    release_date: "1998-06-05(美国)",
    runtime: 103,
    aka: "真人秀 / 楚门秀",
    imdb_id: "tt0120382",
    tmdb_rating: 8.1,
    douban_rating: 8.4,
  },
  {
    tmdb_id: 2000010,
    media_type: "movie",
    title: "辛德勒的名单",
    original_title: "Schindler's List",
    year: 1993,
    poster_path: null,
    overview: "商人辛德勒在纳粹屠犹中倾尽家财，挽救了一千一百多名犹太人的生命。",
    director: "史蒂文·斯皮尔伯格",
    writer: "托马斯·肯尼利 / 斯蒂文·泽里安",
    cast: "连姆·尼森 / 本·金斯利 / 拉尔夫·费因斯",
    genres: "剧情 / 历史 / 战争",
    country: "美国",
    language: "英语 / 德语 / 波兰语",
    release_date: "1993-11-30(美国)",
    runtime: 195,
    aka: "舒特拉的名单",
    imdb_id: "tt0108052",
    tmdb_rating: 8.6,
    douban_rating: 9.0,
  },
  {
    tmdb_id: 2000011,
    media_type: "movie",
    title: "海上钢琴师",
    original_title: "La leggenda del pianista sull'oceano",
    year: 1998,
    poster_path: null,
    overview: "被遗弃在远洋客轮上的钢琴天才1900，终其一生未踏上陆地，与海与琴共舞。",
    director: "朱塞佩·托纳多雷",
    writer: "朱塞佩·托纳多雷",
    cast: "蒂姆·罗斯 / 普路特·泰勒·文斯",
    genres: "剧情 / 音乐",
    country: "意大利",
    language: "英语 / 法语",
    release_date: "2019-11-15(中国大陆)",
    runtime: 165,
    aka: "声光伴我飞 / 传奇1900",
    imdb_id: "tt0120731",
    tmdb_rating: 8.1,
    douban_rating: 8.3,
  },
  {
    tmdb_id: 2000012,
    media_type: "movie",
    title: "三傻大闹宝莱坞",
    original_title: "3 Idiots",
    year: 2009,
    poster_path: null,
    overview: "三个性格迥异的工科生在名校里质疑填鸭教育，用幽默与真诚改写人生。",
    director: "拉吉库马尔·希拉尼",
    writer: "维德胡·维诺德·乔普拉 / 拉吉库马尔·希拉尼",
    cast: "阿米尔·汗 / 卡琳娜·卡普 / 马德哈万",
    genres: "剧情 / 喜剧 / 爱情",
    country: "印度",
    language: "印地语",
    release_date: "2011-12-08(中国大陆)",
    runtime: 171,
    aka: "三个傻瓜 / 作死不离3兄弟",
    imdb_id: "tt1187043",
    tmdb_rating: 8.4,
    douban_rating: 8.6,
  },
  {
    tmdb_id: 2000013,
    media_type: "movie",
    title: "机器人总动员",
    original_title: "WALL·E",
    year: 2008,
    poster_path: null,
    overview: "被遗留在荒废地球的清扫机器人瓦力，邂逅探测机器人伊娃，开启一段星际童话。",
    director: "安德鲁·斯坦顿",
    writer: "安德鲁·斯坦顿 / 皮特·多克特",
    cast: "本·贝尔特 / 艾丽莎·奈特",
    genres: "动画 / 科幻 / 爱情",
    country: "美国",
    language: "英语 / 法语",
    release_date: "2008-06-27(美国)",
    runtime: 98,
    aka: "瓦力 / 星际总动员",
    imdb_id: "tt0910970",
    tmdb_rating: 8.4,
    douban_rating: 8.2,
  },
  {
    tmdb_id: 2000014,
    media_type: "movie",
    title: "放牛班的春天",
    original_title: "Les Choristes",
    year: 2004,
    poster_path: null,
    overview: "失意教师马修用音乐唤醒问题少年们被忽视的天赋与尊严。",
    director: "克里斯托夫·巴拉蒂",
    writer: "克里斯托夫·巴拉蒂 / 菲利普·洛约-泰吕埃",
    cast: "杰拉尔·朱尼奥 / 让-巴蒂斯特·莫尼耶",
    genres: "剧情 / 音乐",
    country: "法国 / 瑞士",
    language: "法语",
    release_date: "2004-03-17(法国)",
    runtime: 97,
    aka: "歌声伴我心 / 唱诗班男孩",
    imdb_id: "tt0372822",
    tmdb_rating: 7.8,
    douban_rating: 7.9,
  },
  {
    tmdb_id: 2000015,
    media_type: "movie",
    title: "大话西游之大圣娶亲",
    original_title: "西游记大结局之仙履奇缘",
    year: 1995,
    poster_path: null,
    overview: "至尊宝在转世与责任之间挣扎，一段笑中带泪的旷世爱情终成遗憾。",
    director: "刘镇伟",
    writer: "刘镇伟 / 吴承恩",
    cast: "周星驰 / 朱茵 / 莫文蔚 / 蔡少芬",
    genres: "喜剧 / 爱情 / 奇幻",
    country: "香港",
    language: "粤语",
    release_date: "2014-10-24(中国大陆)",
    runtime: 95,
    aka: "大话西游2 / 仙履奇缘",
    imdb_id: "tt0118747",
    tmdb_rating: 7.7,
    douban_rating: 8.0,
  },
  {
    tmdb_id: 2000016,
    media_type: "movie",
    title: "无间道",
    original_title: "無間道",
    year: 2002,
    poster_path: null,
    overview: "警方卧底与黑帮内鬼互不知情地渗透对方，身份错位下的一场生死博弈。",
    director: "刘伟强 / 麦兆辉",
    writer: "麦兆辉 / 庄文强",
    cast: "刘德华 / 梁朝伟 / 黄秋生",
    genres: "剧情 / 犯罪 / 悬疑",
    country: "香港",
    language: "粤语",
    release_date: "2002-12-12(香港)",
    runtime: 101,
    aka: "无间道1",
    imdb_id: "tt0338564",
    tmdb_rating: 8.0,
    douban_rating: 7.5,
  },
  {
    tmdb_id: 2000017,
    media_type: "movie",
    title: "春光乍泄",
    original_title: "春光乍洩",
    year: 1997,
    poster_path: null,
    overview: "黎耀辉与何宝荣远走布宜诺斯艾利斯，在爱与离别间反复拉扯。",
    director: "王家卫",
    writer: "王家卫",
    cast: "张国荣 / 梁朝伟 / 张震",
    genres: "剧情 / 爱情 / 同性",
    country: "香港",
    language: "粤语 / 西班牙语",
    release_date: "1997-05-30(香港)",
    runtime: 96,
    aka: "春光乍泄（快乐在一起）",
    imdb_id: "tt0118845",
    tmdb_rating: 7.7,
    douban_rating: 8.2,
  },
  {
    tmdb_id: 2000018,
    media_type: "movie",
    title: "重庆森林",
    original_title: "重慶森林",
    year: 1994,
    poster_path: null,
    overview: "两段互不相干的都市邂逅，在王家卫的镜头里化作关于错过与等待的独白。",
    director: "王家卫",
    writer: "王家卫",
    cast: "林青霞 / 金城武 / 王菲 / 梁朝伟",
    genres: "剧情 / 爱情",
    country: "香港",
    language: "粤语 / 汉语普通话 / 英语",
    release_date: "1994-07-14(香港)",
    runtime: 102,
    aka: "重庆森林（重慶森林）",
    imdb_id: "tt0109424",
    tmdb_rating: 7.8,
    douban_rating: 8.0,
  },
  {
    tmdb_id: 2000019,
    media_type: "movie",
    title: "英雄",
    original_title: "Hero",
    year: 2002,
    poster_path: null,
    overview: "战国刺客无名面见秦王，以三段不同的叙事讲述刺秦背后的家国与天下。",
    director: "张艺谋",
    writer: "张艺谋 / 李冯 / 王斌",
    cast: "李连杰 / 梁朝伟 / 张曼玉 / 陈道明",
    genres: "动作 / 历史 / 武侠",
    country: "中国大陆 / 香港",
    language: "汉语普通话",
    release_date: "2002-12-14(中国大陆)",
    runtime: 99,
    aka: "英雄（Hero）",
    imdb_id: "tt0299977",
    tmdb_rating: 7.0,
    douban_rating: 7.1,
  },
  {
    tmdb_id: 2000020,
    media_type: "movie",
    title: "卧虎藏龙",
    original_title: "Crouching Tiger, Hidden Dragon",
    year: 2000,
    poster_path: null,
    overview: "一代大侠李慕白欲金盆洗手，青冥宝剑失窃，牵出一段江湖儿女的恩怨情仇。",
    director: "李安",
    writer: "王蕙玲 / 詹姆斯·夏慕斯",
    cast: "周润发 / 杨紫琼 / 章子怡",
    genres: "动作 / 武侠 / 冒险",
    country: "台湾 / 香港 / 美国 / 中国大陆",
    language: "汉语普通话",
    release_date: "2000-07-07(台湾)",
    runtime: 120,
    aka: "卧虎藏龙（Crouching Tiger）",
    imdb_id: "tt0190332",
    tmdb_rating: 7.6,
    douban_rating: 7.1,
  },
  {
    tmdb_id: 2000021,
    media_type: "movie",
    title: "让子弹飞",
    original_title: "让子弹飞",
    year: 2010,
    poster_path: null,
    overview: "民国乱世，土匪冒充县长进城，与恶霸黄四郎斗智斗勇，黑色幽默酣畅淋漓。",
    director: "姜文",
    writer: "姜文 / 述平 / 郭俊立",
    cast: "姜文 / 葛优 / 周润发 / 刘嘉玲",
    genres: "剧情 / 喜剧 / 动作",
    country: "中国大陆 / 香港",
    language: "汉语普通话 / 山西话",
    release_date: "2010-12-16(中国大陆)",
    runtime: 132,
    aka: "让子弹飞一会儿",
    imdb_id: "tt1535602",
    tmdb_rating: 7.3,
    douban_rating: 6.9,
  },
  {
    tmdb_id: 2000022,
    media_type: "movie",
    title: "鬼子来了",
    original_title: "鬼子来了",
    year: 2000,
    poster_path: null,
    overview: "抗战时期，村民意外看管两名日军俘虏，荒诞与悲剧在乡土中国悄然上演。",
    director: "姜文",
    writer: "姜文 / 史建全 / 述平",
    cast: "姜文 / 香川照之 / 袁丁",
    genres: "剧情 / 喜剧 / 战争",
    country: "中国大陆",
    language: "汉语普通话 / 日语 / 唐山话",
    release_date: "2000-05-12(戛纳)",
    runtime: 139,
    aka: "鬼子来了（Devils on the Doorstep）",
    imdb_id: "tt0210015",
    tmdb_rating: 7.9,
    douban_rating: 8.1,
  },
  {
    tmdb_id: 2000023,
    media_type: "movie",
    title: "阳光灿烂的日子",
    original_title: "阳光灿烂的日子",
    year: 1994,
    poster_path: null,
    overview: "文革年代的北京大院里，少年马小军在荷尔蒙与迷茫中肆意生长。",
    director: "姜文",
    writer: "姜文 / 王朔",
    cast: "夏雨 / 宁静 / 耿乐",
    genres: "剧情",
    country: "中国大陆",
    language: "汉语普通话",
    release_date: "1994-09-09(中国大陆)",
    runtime: 134,
    aka: "阳光灿烂的日子（In the Heat of the Sun）",
    imdb_id: "tt0118843",
    tmdb_rating: 7.5,
    douban_rating: 7.9,
  },
  {
    tmdb_id: 2000024,
    media_type: "movie",
    title: "活着",
    original_title: "活着",
    year: 1994,
    poster_path: null,
    overview: "福贵一家在时代洪流中被反复抛掷，唯以活着本身对抗无常的命运。",
    director: "张艺谋",
    writer: "芦苇 / 余华",
    cast: "葛优 / 巩俐",
    genres: "剧情 / 历史 / 家庭",
    country: "中国大陆 / 香港",
    language: "汉语普通话",
    release_date: "1994-05-17(戛纳)",
    runtime: 132,
    aka: "活着（To Live）",
    imdb_id: "tt0110081",
    tmdb_rating: 8.2,
    douban_rating: 8.4,
  },
  {
    tmdb_id: 2000025,
    media_type: "movie",
    title: "红高粱",
    original_title: "红高粱",
    year: 1987,
    poster_path: null,
    overview: "在漫野高粱地里，九儿与轿夫余占鳌以炽烈的生命力书写抗日传奇。",
    director: "张艺谋",
    writer: "陈剑雨 / 朱伟 / 莫言",
    cast: "姜文 / 巩俐",
    genres: "剧情 / 历史 / 战争",
    country: "中国大陆",
    language: "汉语普通话",
    release_date: "1987-10-01(中国大陆)",
    runtime: 91,
    aka: "红高粱（Red Sorghum）",
    imdb_id: "tt0092884",
    tmdb_rating: 7.3,
    douban_rating: 7.0,
  },
  {
    tmdb_id: 2000026,
    media_type: "movie",
    title: "大红灯笼高高挂",
    original_title: "大紅燈籠高高掛",
    year: 1991,
    poster_path: null,
    overview: "年轻女学生嫁入深宅大院，在妻妾争宠的规矩里逐渐迷失自我。",
    director: "张艺谋",
    writer: "倪震 / 苏童",
    cast: "巩俐 / 马精武 / 何赛飞",
    genres: "剧情",
    country: "中国大陆 / 香港 / 台湾",
    language: "汉语普通话",
    release_date: "1991-12-20(中国大陆)",
    runtime: 125,
    aka: "大红灯笼高高挂（Raise the Red Lantern）",
    imdb_id: "tt0101410",
    tmdb_rating: 7.8,
    douban_rating: 8.0,
  },
  {
    tmdb_id: 2000027,
    media_type: "movie",
    title: "饮食男女",
    original_title: "飲食男女",
    year: 1994,
    poster_path: null,
    overview: "退休名厨老朱与三个女儿围着餐桌，用一桌饭菜道尽家庭与人生的聚散。",
    director: "李安",
    writer: "李安 / 王蕙玲 / 詹姆斯·夏慕斯",
    cast: "郎雄 / 吴倩莲 / 杨贵媚 / 王渝文",
    genres: "剧情 / 爱情",
    country: "台湾 / 美国",
    language: "汉语普通话",
    release_date: "1994-07-02(台湾)",
    runtime: 124,
    aka: "饮食男女（Eat Drink Man Woman）",
    imdb_id: "tt0107924",
    tmdb_rating: 7.7,
    douban_rating: 7.9,
  },
  {
    tmdb_id: 2000028,
    media_type: "movie",
    title: "喜宴",
    original_title: "喜宴",
    year: 1993,
    poster_path: null,
    overview: "定居美国的同性恋青年为安抚父母假结婚，一场传统喜宴掀开代际与身份的真相。",
    director: "李安",
    writer: "李安 / 冯光远 / 詹姆斯·夏慕斯",
    cast: "赵文瑄 / 金素梅 / 归亚蕾 / 郎雄",
    genres: "剧情 / 喜剧 / 爱情 / 同性",
    country: "台湾 / 美国",
    language: "汉语普通话 / 英语",
    release_date: "1993-08-04(美国)",
    runtime: 106,
    aka: "喜宴（The Wedding Banquet）",
    imdb_id: "tt0107156",
    tmdb_rating: 7.6,
    douban_rating: 7.4,
  },
  {
    tmdb_id: 2000029,
    media_type: "movie",
    title: "断背山",
    original_title: "Brokeback Mountain",
    year: 2005,
    poster_path: null,
    overview: "两名牛仔在放牧岁月里萌生禁忌之情，此后数十年在世俗与思念中彼此牵绊。",
    director: "李安",
    writer: "黛安娜·欧莎娜 / 吉姆·拉斯克",
    cast: "希斯·莱杰 / 杰克·吉伦哈尔 / 米歇尔·威廉姆斯",
    genres: "剧情 / 爱情 / 同性",
    country: "美国",
    language: "英语",
    release_date: "2005-12-09(美国)",
    runtime: 134,
    aka: "断臂山",
    imdb_id: "tt0388795",
    tmdb_rating: 7.6,
    douban_rating: 8.0,
  },
  {
    tmdb_id: 2000030,
    media_type: "movie",
    title: "少年派的奇幻漂流",
    original_title: "Life of Pi",
    year: 2012,
    poster_path: null,
    overview: "海难幸存少年派与一只孟加拉虎漂流太平洋，在信仰与生存间寻找意义。",
    director: "李安",
    writer: "戴维·马戈",
    cast: "苏拉·沙玛 / 伊尔凡·可汗 / 塔布",
    genres: "剧情 / 冒险 / 奇幻",
    country: "美国 / 台湾 / 英国 / 加拿大",
    language: "英语 / 汉语普通话 / 泰米尔语",
    release_date: "2012-11-22(中国大陆)",
    runtime: 127,
    aka: "少年Pi的奇幻漂流",
    imdb_id: "tt0454876",
    tmdb_rating: 7.9,
    douban_rating: 8.1,
  },
  {
    tmdb_id: 2000031,
    media_type: "movie",
    title: "指环王：王者无敌",
    original_title: "The Lord of the Rings: The Return of the King",
    year: 2003,
    poster_path: null,
    overview: "魔戒远征队迎来最终决战，佛罗多必须在末日火山放下至尊魔戒拯救中土。",
    director: "彼得·杰克逊",
    writer: "弗兰·威尔士 / 菲利帕·鲍恩斯 / 彼得·杰克逊",
    cast: "维戈·莫特森 / 伊利亚·伍德 / 西恩·奥斯汀",
    genres: "剧情 / 动作 / 奇幻 / 冒险",
    country: "美国 / 新西兰",
    language: "英语 / 辛达林语",
    release_date: "2004-03-12(中国大陆)",
    runtime: 201,
    aka: "魔戒3：王者再临",
    imdb_id: "tt0167260",
    tmdb_rating: 8.5,
    douban_rating: 8.9,
  },
  {
    tmdb_id: 2000032,
    media_type: "movie",
    title: "霍比特人：意外之旅",
    original_title: "The Hobbit: An Unexpected Journey",
    year: 2012,
    poster_path: null,
    overview: "霍比特人比尔博随矮人远征孤山，途中邂逅咕噜，得到改变命运的魔戒。",
    director: "彼得·杰克逊",
    writer: "弗兰·威尔士 / 菲利帕·鲍恩斯 / 彼得·杰克逊",
    cast: "马丁·弗瑞曼 / 伊恩·麦克莱恩 / 理查德·阿米蒂奇",
    genres: "奇幻 / 冒险",
    country: "美国 / 新西兰",
    language: "英语",
    release_date: "2013-02-22(中国大陆)",
    runtime: 169,
    aka: "哈比人：意外旅程",
    imdb_id: "tt0903624",
    tmdb_rating: 7.3,
    douban_rating: 7.0,
  },
  {
    tmdb_id: 2000033,
    media_type: "movie",
    title: "阿凡达",
    original_title: "Avatar",
    year: 2009,
    poster_path: null,
    overview: "瘫痪士兵杰克化身纳威人潜入潘多拉，却在殖民与守护之间做出抉择。",
    director: "詹姆斯·卡梅隆",
    writer: "詹姆斯·卡梅隆",
    cast: "萨姆·沃辛顿 / 佐伊·索尔达娜 / 西格妮·韦弗",
    genres: "动作 / 科幻 / 冒险",
    country: "美国",
    language: "英语 / 纳威语",
    release_date: "2010-01-04(中国大陆)",
    runtime: 162,
    aka: "阿凡达（Avatar）",
    imdb_id: "tt0499549",
    tmdb_rating: 7.6,
    douban_rating: 7.4,
  },
  {
    tmdb_id: 2000034,
    media_type: "movie",
    title: "复仇者联盟4：终局之战",
    original_title: "Avengers: Endgame",
    year: 2019,
    poster_path: null,
    overview: "响指之后，幸存的复仇者穿越时空收回无限宝石，与灭霸展开最后一战。",
    director: "安东尼·罗素 / 乔·罗素",
    writer: "克里斯托弗·马库斯 / 斯蒂芬·麦克菲利",
    cast: "小罗伯特·唐尼 / 克里斯·埃文斯 / 马克·鲁法洛",
    genres: "动作 / 科幻 / 奇幻",
    country: "美国",
    language: "英语",
    release_date: "2019-04-24(中国大陆)",
    runtime: 181,
    aka: "复仇者联盟：终局之战",
    imdb_id: "tt4154796",
    tmdb_rating: 8.3,
    douban_rating: 8.4,
  },
  {
    tmdb_id: 2000035,
    media_type: "movie",
    title: "蝙蝠侠：黑暗骑士",
    original_title: "The Dark Knight",
    year: 2008,
    poster_path: null,
    overview: "哥谭市陷入混乱，蝙蝠侠与以小丑为首的罪恶展开一场关于秩序的较量。",
    director: "克里斯托弗·诺兰",
    writer: "乔纳森·诺兰 / 克里斯托弗·诺兰 / 大卫·S·高耶",
    cast: "克里斯蒂安·贝尔 / 希斯·莱杰 / 艾伦·艾克哈特",
    genres: "动作 / 犯罪 / 悬疑",
    country: "美国 / 英国",
    language: "英语",
    release_date: "2008-07-18(美国)",
    runtime: 152,
    aka: "蝙蝠侠前传2：黑暗骑士",
    imdb_id: "tt0468569",
    tmdb_rating: 8.5,
    douban_rating: 8.8,
  },
  {
    tmdb_id: 2000036,
    media_type: "movie",
    title: "寄生虫",
    original_title: "기생충",
    year: 2019,
    poster_path: null,
    overview: "穷困的金家逐一渗透进富裕的朴家，阶层鸿沟在一次意外中轰然崩塌。",
    director: "奉俊昊",
    writer: "奉俊昊 / 韩进元",
    cast: "宋康昊 / 李善均 / 赵汝贞 / 崔宇植",
    genres: "剧情 / 喜剧 / 惊悚",
    country: "韩国",
    language: "韩语",
    release_date: "2019-05-30(韩国)",
    runtime: 132,
    aka: "寄生上流",
    imdb_id: "tt6751668",
    tmdb_rating: 8.5,
    douban_rating: 8.8,
  },
  {
    tmdb_id: 2000037,
    media_type: "movie",
    title: "老男孩",
    original_title: "올드보이",
    year: 2003,
    poster_path: null,
    overview: "被无故囚禁十五年的男子重获自由，只为找出囚禁者并揭开复仇的真相。",
    director: "朴赞郁",
    writer: "朴赞郁 / 黄兆尹 / 林俊亨",
    cast: "崔岷植 / 刘智泰 / 姜惠贞",
    genres: "剧情 / 动作 / 悬疑 / 惊悚",
    country: "韩国",
    language: "韩语",
    release_date: "2003-11-21(韩国)",
    runtime: 120,
    aka: "原罪（Oldboy）",
    imdb_id: "tt0364569",
    tmdb_rating: 8.2,
    douban_rating: 7.8,
  },
  {
    tmdb_id: 2000038,
    media_type: "movie",
    title: "杀人回忆",
    original_title: "살인의 추억",
    year: 2003,
    poster_path: null,
    overview: "1980年代韩国乡间连环奸杀案，两位警探在真相无望中逐渐崩溃。",
    director: "奉俊昊",
    writer: "奉俊昊 / 沈成宝 / 金光林",
    cast: "宋康昊 / 金相庆 / 金雷河",
    genres: "剧情 / 犯罪 / 悬疑 / 惊悚",
    country: "韩国",
    language: "韩语",
    release_date: "2003-05-02(韩国)",
    runtime: 132,
    aka: "谋杀回忆",
    imdb_id: "tt0353969",
    tmdb_rating: 8.1,
    douban_rating: 8.2,
  },
  {
    tmdb_id: 2000039,
    media_type: "movie",
    title: "美丽人生",
    original_title: "La vita è bella",
    year: 1997,
    poster_path: null,
    overview: "父亲用一场善意的谎言，在纳粹集中营里为儿子守护童年的纯真。",
    director: "罗伯托·贝尼尼",
    writer: "文森佐·克拉米 / 罗伯托·贝尼尼",
    cast: "罗伯托·贝尼尼 / 尼可莱塔·布拉斯基 / 乔治·坎塔里尼",
    genres: "剧情 / 喜剧 / 战争",
    country: "意大利",
    language: "意大利语 / 德语",
    release_date: "1997-12-20(意大利)",
    runtime: 116,
    aka: "一个快乐的传说",
    imdb_id: "tt0118799",
    tmdb_rating: 8.5,
    douban_rating: 8.7,
  },
  {
    tmdb_id: 2000040,
    media_type: "movie",
    title: "天堂电影院",
    original_title: "Nuovo Cinema Paradiso",
    year: 1988,
    poster_path: null,
    overview: "放映员与小镇男孩在电影院里结下忘年交，胶片串起一生对电影与爱的眷恋。",
    director: "朱塞佩·托纳多雷",
    writer: "朱塞佩·托纳多雷 / 瓦娜·波利",
    cast: "菲利浦·诺瓦雷 / 萨瓦特利·卡西欧 / 雅克·贝汉",
    genres: "剧情 / 爱情",
    country: "意大利 / 法国",
    language: "意大利语 / 西班牙语",
    release_date: "1988-11-17(意大利)",
    runtime: 155,
    aka: "星光伴我心 / 新天堂乐园",
    imdb_id: "tt0095765",
    tmdb_rating: 8.5,
    douban_rating: 8.9,
  },
  {
    tmdb_id: 2000041,
    media_type: "movie",
    title: "西西里的美丽传说",
    original_title: "Malèna",
    year: 2000,
    poster_path: null,
    overview: "二战小镇上，少年雷纳多暗恋着美丽寡妇玛莲娜，见证了她被流言吞噬的悲剧。",
    director: "朱塞佩·托纳多雷",
    writer: "朱塞佩·托纳多雷 / 卢恰诺·温琴佐尼",
    cast: "莫妮卡·贝鲁奇 / 朱塞佩·苏尔法罗",
    genres: "剧情 / 爱情 / 战争",
    country: "意大利 / 美国",
    language: "意大利语 / 英语",
    release_date: "2000-10-27(意大利)",
    runtime: 109,
    aka: "真爱伴我行",
    imdb_id: "tt0213847",
    tmdb_rating: 7.5,
    douban_rating: 7.3,
  },
  {
    tmdb_id: 2000042,
    media_type: "movie",
    title: "情书",
    original_title: "Love Letter",
    year: 1995,
    poster_path: null,
    overview: "未婚妻渡边博子在逝者忌日寄出一封信，却收到同名同姓女孩的回信，牵出青春暗恋。",
    director: "岩井俊二",
    writer: "岩井俊二",
    cast: "中山美穗 / 柏原崇 / 丰川悦司",
    genres: "剧情 / 爱情",
    country: "日本",
    language: "日语",
    release_date: "1995-03-25(日本)",
    runtime: 117,
    aka: "情书（Love Letter）",
    imdb_id: "tt0113822",
    tmdb_rating: 7.7,
    douban_rating: 8.1,
  },
  {
    tmdb_id: 2000043,
    media_type: "movie",
    title: "花样年华",
    original_title: "花樣年華",
    year: 2000,
    poster_path: null,
    overview: "比邻而居的周慕云与苏丽珍，在各自伴侣出轨后靠近，却始终隔着克制的爱。",
    director: "王家卫",
    writer: "王家卫",
    cast: "梁朝伟 / 张曼玉",
    genres: "剧情 / 爱情",
    country: "香港",
    language: "粤语 / 上海话",
    release_date: "2000-09-29(香港)",
    runtime: 98,
    aka: "花样年华（In the Mood for Love）",
    imdb_id: "tt0118694",
    tmdb_rating: 8.0,
    douban_rating: 7.8,
  },
  {
    tmdb_id: 2000044,
    media_type: "movie",
    title: "2046",
    original_title: "2046",
    year: 2004,
    poster_path: null,
    overview: "作家周慕云流连于不同女子之间，用一部小说《2046》祭奠再也回不去的时光。",
    director: "王家卫",
    writer: "王家卫",
    cast: "梁朝伟 / 章子怡 / 王菲 / 木村拓哉",
    genres: "剧情 / 爱情 / 科幻",
    country: "香港",
    language: "粤语 / 汉语普通话 / 日语",
    release_date: "2004-09-28(香港)",
    runtime: 129,
    aka: "2046（二零四六）",
    imdb_id: "tt0039911",
    tmdb_rating: 7.4,
    douban_rating: 7.8,
  },
  {
    tmdb_id: 2000045,
    media_type: "movie",
    title: "东邪西毒",
    original_title: "東邪西毒",
    year: 1994,
    poster_path: null,
    overview: "沙漠客栈里，一众武林高手在爱恨纠葛中各自漂泊，错过与遗憾是永恒的主题。",
    director: "王家卫",
    writer: "王家卫 / 金庸",
    cast: "张国荣 / 林青霞 / 梁朝伟 / 张曼玉",
    genres: "剧情 / 动作 / 爱情",
    country: "香港",
    language: "粤语 / 汉语普通话",
    release_date: "1994-09-17(香港)",
    runtime: 100,
    aka: "东邪西毒（Ashes of Time）",
    imdb_id: "tt0109684",
    tmdb_rating: 7.3,
    douban_rating: 7.5,
  },
  {
    tmdb_id: 2000046,
    media_type: "movie",
    title: "一代宗师",
    original_title: "一代宗師",
    year: 2013,
    poster_path: null,
    overview: "咏春宗师叶问在时代的动荡中坚守武道，与宫二演绎一段克制的武林情缘。",
    director: "王家卫",
    writer: "王家卫 / 邹静之 / 徐浩峰",
    cast: "梁朝伟 / 章子怡 / 张震 / 宋慧乔",
    genres: "剧情 / 动作 / 爱情 / 传记",
    country: "香港 / 中国大陆",
    language: "粤语 / 汉语普通话",
    release_date: "2013-01-08(中国大陆)",
    runtime: 130,
    aka: "一代宗师（The Grandmaster）",
    imdb_id: "tt1462900",
    tmdb_rating: 6.5,
    douban_rating: 6.7,
  },
  {
    tmdb_id: 2000047,
    media_type: "movie",
    title: "色，戒",
    original_title: "色，戒",
    year: 2007,
    poster_path: null,
    overview: "女学生王佳芝潜入汉奸易先生身边实施刺杀，却在情欲与任务间动摇。",
    director: "李安",
    writer: "王蕙玲 / 詹姆斯·夏慕斯 / 李安",
    cast: "梁朝伟 / 汤唯 / 王力宏",
    genres: "剧情 / 爱情 / 惊悚",
    country: "台湾 / 美国 / 中国大陆 / 香港",
    language: "汉语普通话 / 粤语 / 上海话 / 英语",
    release_date: "2007-11-01(中国大陆)",
    runtime: 158,
    aka: "色戒（Lust, Caution）",
    imdb_id: "tt0808358",
    tmdb_rating: 7.2,
    douban_rating: 6.8,
  },
  {
    tmdb_id: 2000048,
    media_type: "movie",
    title: "疯狂动物城",
    original_title: "Zootopia",
    year: 2016,
    poster_path: null,
    overview: "兔子警官朱迪与狐狸尼克联手破案，在动物乌托邦里打破偏见寻找真相。",
    director: "拜伦·霍华德 / 瑞奇·摩尔",
    writer: "拜伦·霍华德 / 瑞奇·摩尔 / 吉姆·里尔顿",
    cast: "金妮弗·古德温 / 杰森·贝特曼",
    genres: "动画 / 喜剧 / 冒险",
    country: "美国",
    language: "英语",
    release_date: "2016-03-04(中国大陆)",
    runtime: 109,
    aka: "优兽大都会 / 动物方城市",
    imdb_id: "tt2948356",
    tmdb_rating: 8.0,
    douban_rating: 7.7,
  },
  {
    tmdb_id: 2000049,
    media_type: "movie",
    title: "寻梦环游记",
    original_title: "Coco",
    year: 2017,
    poster_path: null,
    overview: "男孩米格踏入亡灵世界，在音乐与记忆中寻回被遗忘的家族之爱。",
    director: "李·昂克里奇 / 阿德里安·莫利纳",
    writer: "李·昂克里奇 / 阿德里安·莫利纳 / 马修·奥德里奇",
    cast: "安东尼·冈萨雷斯 / 盖尔·加西亚·贝纳尔",
    genres: "动画 / 音乐 / 奇幻",
    country: "美国",
    language: "英语 / 西班牙语",
    release_date: "2017-11-24(中国大陆)",
    runtime: 105,
    aka: "可可夜总会",
    imdb_id: "tt2380307",
    tmdb_rating: 8.2,
    douban_rating: 8.7,
  },
  {
    tmdb_id: 2000050,
    media_type: "movie",
    title: "飞屋环游记",
    original_title: "Up",
    year: 2009,
    poster_path: null,
    overview: "老卡尔用气球拽着房子飞向南美，途中与小男孩罗素开启一场迟到的人生冒险。",
    director: "彼特·道格特 / 鲍勃·彼德森",
    writer: "彼特·道格特 / 鲍勃·彼德森",
    cast: "爱德华·阿斯纳 / 乔丹·长井",
    genres: "动画 / 喜剧 / 冒险",
    country: "美国",
    language: "英语",
    release_date: "2009-08-04(中国大陆)",
    runtime: 96,
    aka: "冲天救兵 / 天外奇迹",
    imdb_id: "tt1049413",
    tmdb_rating: 8.0,
    douban_rating: 7.7,
  },
  {
    tmdb_id: 2000051,
    media_type: "movie",
    title: "冰雪奇缘",
    original_title: "Frozen",
    year: 2013,
    poster_path: null,
    overview: "阿伦黛尔公主安娜踏上寻姐之旅，解开姐姐冰雪魔法的诅咒与心结。",
    director: "克里斯·巴克 / 珍妮弗·李",
    writer: "珍妮弗·李 / 克里斯·巴克",
    cast: "克里斯汀·贝尔 / 伊迪娜·门泽尔",
    genres: "动画 / 歌舞 / 奇幻",
    country: "美国",
    language: "英语",
    release_date: "2014-02-05(中国大陆)",
    runtime: 102,
    aka: "魔雪奇缘",
    imdb_id: "tt2294629",
    tmdb_rating: 7.2,
    douban_rating: 6.9,
  },
  {
    tmdb_id: 2000052,
    media_type: "movie",
    title: "你的名字。",
    original_title: "君の名は。",
    year: 2016,
    poster_path: null,
    overview: "乡村少女与东京少年在梦中互换身体，循着命运的丝线寻找彼此与那场彗星之灾。",
    director: "新海诚",
    writer: "新海诚",
    cast: "神木隆之介 / 上白石萌音",
    genres: "动画 / 爱情 / 奇幻",
    country: "日本",
    language: "日语",
    release_date: "2016-12-02(日本)",
    runtime: 106,
    aka: "你的名字（Your Name）",
    imdb_id: "tt5311514",
    tmdb_rating: 8.4,
    douban_rating: 8.4,
  },
  {
    tmdb_id: 2000053,
    media_type: "movie",
    title: "天气之子",
    original_title: "天気の子",
    year: 2019,
    poster_path: null,
    overview: "少年帆帆逃到东京，遇见能呼风唤雨的少女阳菜，在晴雨与抉择间守护所爱。",
    director: "新海诚",
    writer: "新海诚",
    cast: "醍醐虎汰朗 / 森七菜",
    genres: "动画 / 爱情 / 奇幻",
    country: "日本",
    language: "日语",
    release_date: "2019-11-01(中国大陆)",
    runtime: 114,
    aka: "Weathering with You",
    imdb_id: "tt9426214",
    tmdb_rating: 7.4,
    douban_rating: 7.1,
  },
  {
    tmdb_id: 2000054,
    media_type: "movie",
    title: "铃芽之旅",
    original_title: "すずめの戸締まり",
    year: 2022,
    poster_path: null,
    overview: "少女铃芽遇见闭门师草太，踏上关闭灾难之门的旅程，也直面母亲的逝去。",
    director: "新海诚",
    writer: "新海诚",
    cast: "原菜乃华 / 松村北斗",
    genres: "动画 / 奇幻 / 冒险",
    country: "日本",
    language: "日语",
    release_date: "2022-11-11(日本)",
    runtime: 121,
    aka: "Suzume",
    imdb_id: "tt18270962",
    tmdb_rating: 7.5,
    douban_rating: 7.6,
  },
  {
    tmdb_id: 2000055,
    media_type: "movie",
    title: "哈尔的移动城堡",
    original_title: "ハウルの動く城",
    year: 2004,
    poster_path: null,
    overview: "被诅咒成老妇的苏菲闯入魔法师哈尔的移动城堡，在战争与爱中找回自我。",
    director: "宫崎骏",
    writer: "宫崎骏 / 黛安娜·温恩·琼斯",
    cast: "倍赏千惠子 / 木村拓哉",
    genres: "动画 / 奇幻 / 冒险",
    country: "日本",
    language: "日语",
    release_date: "2024-04-30(中国大陆)",
    runtime: 119,
    aka: "豪尔的机动城堡",
    imdb_id: "tt0347149",
    tmdb_rating: 8.2,
    douban_rating: 7.9,
  },
  {
    tmdb_id: 2000056,
    media_type: "movie",
    title: "龙猫",
    original_title: "となりのトトロ",
    year: 1988,
    poster_path: null,
    overview: "两姐妹搬进乡间老屋，遇见森林精灵龙猫，在童真里感受自然的温柔。",
    director: "宫崎骏",
    writer: "宫崎骏",
    cast: "日高法子 / 坂本千夏",
    genres: "动画 / 奇幻 / 冒险",
    country: "日本",
    language: "日语",
    release_date: "2018-12-14(中国大陆)",
    runtime: 86,
    aka: "邻家的豆豆龙",
    imdb_id: "tt0096283",
    tmdb_rating: 8.1,
    douban_rating: 8.6,
  },
  {
    tmdb_id: 2000057,
    media_type: "movie",
    title: "天空之城",
    original_title: "天空の城ラピュタ",
    year: 1986,
    poster_path: null,
    overview: "少女希达与少年巴斯追寻传说中的浮空岛屿拉普达，对抗贪婪的军方与海盗。",
    director: "宫崎骏",
    writer: "宫崎骏",
    cast: "田中真弓 / 横泽启子",
    genres: "动画 / 奇幻 / 冒险",
    country: "日本",
    language: "日语",
    release_date: "2023-06-01(中国大陆)",
    runtime: 124,
    aka: "空中城堡",
    imdb_id: "tt0092067",
    tmdb_rating: 7.9,
    douban_rating: 7.4,
  },
  {
    tmdb_id: 2000058,
    media_type: "movie",
    title: "风之谷",
    original_title: "風の谷のナウシカ",
    year: 1984,
    poster_path: null,
    overview: "腐海边缘的少女娜乌西卡以勇气与悲悯，试图调和人类与自然的千年仇恨。",
    director: "宫崎骏",
    writer: "宫崎骏",
    cast: "岛本须美 / 京田尚子",
    genres: "动画 / 科幻 / 冒险",
    country: "日本",
    language: "日语",
    release_date: "2018-12-14(中国大陆)",
    runtime: 117,
    aka: "风之谷的娜乌西卡",
    imdb_id: "tt0087544",
    tmdb_rating: 7.7,
    douban_rating: 7.4,
  },
  {
    tmdb_id: 2000059,
    media_type: "movie",
    title: "红猪",
    original_title: "紅の豚",
    year: 1992,
    poster_path: null,
    overview: "被诅咒成猪的飞行员波鲁克，在亚得里亚海的天空下守护着自由与浪漫。",
    director: "宫崎骏",
    writer: "宫崎骏",
    cast: "森山周一郎 / 加藤登纪子",
    genres: "动画 / 冒险",
    country: "日本",
    language: "日语 / 意大利语",
    release_date: "2023-11-17(中国大陆)",
    runtime: 93,
    aka: "飞天红猪侠",
    imdb_id: "tt0104652",
    tmdb_rating: 7.6,
    douban_rating: 7.6,
  },
  {
    tmdb_id: 2000060,
    media_type: "movie",
    title: "起风了",
    original_title: "風立ちぬ",
    year: 2013,
    poster_path: null,
    overview: "飞机设计师堀越二郎在战乱年代追逐飞行之梦，与病弱的菜穗子相守相别。",
    director: "宫崎骏",
    writer: "宫崎骏",
    cast: "庵野秀明 / 泷本美织",
    genres: "动画 / 剧情 / 爱情",
    country: "日本",
    language: "日语",
    release_date: "2013-07-20(日本)",
    runtime: 126,
    aka: "风起（The Wind Rises）",
    imdb_id: "tt2013293",
    tmdb_rating: 7.5,
    douban_rating: 7.8,
  },
  {
    tmdb_id: 2000061,
    media_type: "movie",
    title: "幽灵公主",
    original_title: "もののけ姫",
    year: 1997,
    poster_path: null,
    overview: "少年阿席达卡为解诅咒踏入森林，卷入人类与山兽神之间的生存之战。",
    director: "宫崎骏",
    writer: "宫崎骏",
    cast: "松田洋治 / 石田百合子",
    genres: "动画 / 奇幻 / 冒险",
    country: "日本",
    language: "日语",
    release_date: "2018-12-14(中国大陆)",
    runtime: 134,
    aka: "魔法公主",
    imdb_id: "tt0119698",
    tmdb_rating: 8.2,
    douban_rating: 7.8,
  },
  {
    tmdb_id: 2000062,
    media_type: "movie",
    title: "魔女宅急便",
    original_title: "魔女の宅急便",
    year: 1989,
    poster_path: null,
    overview: "小魔女琪琪离开家乡独立生活，用飞行快递在陌生城市里寻找属于自己的位置。",
    director: "宫崎骏",
    writer: "宫崎骏",
    cast: "高山南 / 佐久间玲",
    genres: "动画 / 奇幻",
    country: "日本",
    language: "日语",
    release_date: "2019-01-01(中国大陆)",
    runtime: 103,
    aka: "小魔女限时专送",
    imdb_id: "tt0097814",
    tmdb_rating: 7.7,
    douban_rating: 8.2,
  },
  {
    tmdb_id: 2000063,
    media_type: "movie",
    title: "悬崖上的金鱼姬",
    original_title: "崖の上のポニョ",
    year: 2008,
    poster_path: null,
    overview: "金鱼姬波妞渴望变成人类，与男孩宗介的纯真友谊引发了一场海洋的奇迹。",
    director: "宫崎骏",
    writer: "宫崎骏",
    cast: "山口智子 / 长岛一茂",
    genres: "动画 / 奇幻 / 冒险",
    country: "日本",
    language: "日语",
    release_date: "2020-12-31(中国大陆)",
    runtime: 101,
    aka: "崖上的波妞",
    imdb_id: "tt0876563",
    tmdb_rating: 7.5,
    douban_rating: 7.7,
  },
  {
    tmdb_id: 2000064,
    media_type: "movie",
    title: "借东西的小人阿莉埃蒂",
    original_title: "借りぐらしのアリエッティ",
    year: 2010,
    poster_path: null,
    overview: "住在地板下的小人少女阿莉埃蒂，与被她窥见的少年翔之间萌生跨越尺寸的羁绊。",
    director: "米林宏昌",
    writer: "宫崎骏 / 丹羽圭子",
    cast: "志田未来 / 神木隆之介",
    genres: "动画 / 奇幻 / 冒险",
    country: "日本",
    language: "日语",
    release_date: "2010-07-17(日本)",
    runtime: 94,
    aka: "借物少女艾莉缇",
    imdb_id: "tt1562047",
    tmdb_rating: 7.6,
    douban_rating: 7.2,
  },
  {
    tmdb_id: 2000065,
    media_type: "movie",
    title: "银翼杀手2049",
    original_title: "Blade Runner 2049",
    year: 2017,
    poster_path: null,
    overview: "新一代复制人K追查尘封秘密，逐渐逼近关于人与造物的终极谜题。",
    director: "丹尼斯·维伦纽瓦",
    writer: "汉普顿·范彻 / 迈克尔·格林",
    cast: "瑞恩·高斯林 / 哈里森·福特 / 安娜·德·阿玛斯",
    genres: "科幻 / 悬疑 / 惊悚",
    country: "美国",
    language: "英语 / 芬兰语 / 日语",
    release_date: "2017-11-10(中国大陆)",
    runtime: 164,
    aka: "银翼杀手2",
    imdb_id: "tt1856101",
    tmdb_rating: 7.9,
    douban_rating: 7.4,
  },
  {
    tmdb_id: 2000066,
    media_type: "movie",
    title: "沙丘",
    original_title: "Dune",
    year: 2021,
    poster_path: null,
    overview: "少年保罗随家族接管沙漠星球厄拉科斯，在香料与权谋中踏上命运的英雄之旅。",
    director: "丹尼斯·维伦纽瓦",
    writer: "乔·斯派茨 / 丹尼斯·维伦纽瓦 / 艾瑞克·罗斯",
    cast: "提莫西·查拉梅 / 丽贝卡·弗格森 / 奥斯卡·伊萨克",
    genres: "科幻 / 冒险",
    country: "美国 / 加拿大",
    language: "英语",
    release_date: "2021-10-22(中国大陆)",
    runtime: 155,
    aka: "沙丘（Dune：Part One）",
    imdb_id: "tt1160419",
    tmdb_rating: 7.7,
    douban_rating: 8.1,
  },
  {
    tmdb_id: 2000067,
    media_type: "movie",
    title: "降临",
    original_title: "Arrival",
    year: 2016,
    poster_path: null,
    overview: "语言学家露易丝受命破译外星飞船的文字，在沟通中重新理解了时间与人生。",
    director: "丹尼斯·维伦纽瓦",
    writer: "埃里克·海瑟尔 / 姜峯楠",
    cast: "艾米·亚当斯 / 杰瑞米·雷纳 / 福里斯特·惠特克",
    genres: "科幻 / 悬疑",
    country: "美国",
    language: "英语 / 汉语普通话 / 俄语",
    release_date: "2017-01-20(中国大陆)",
    runtime: 116,
    aka: "异星接触 / 你一生的故事",
    imdb_id: "tt2543164",
    tmdb_rating: 7.6,
    douban_rating: 7.8,
  },
  {
    tmdb_id: 2000068,
    media_type: "movie",
    title: "疯狂的麦克斯：狂暴之路",
    original_title: "Mad Max: Fury Road",
    year: 2015,
    poster_path: null,
    overview: "末世废土上，麦克斯与女战士弗瑞奥萨驾车狂飙，护送逃离暴君的五位妻子。",
    director: "乔治·米勒",
    writer: "乔治·米勒 / 布伦丹·麦卡锡 / 尼克·拉图里",
    cast: "汤姆·哈迪 / 查理兹·塞隆 / 尼古拉斯·霍尔特",
    genres: "动作 / 科幻 / 冒险",
    country: "澳大利亚 / 美国",
    language: "英语",
    release_date: "2015-05-15(中国大陆)",
    runtime: 120,
    aka: "末日先锋：战甲飞车",
    imdb_id: "tt1392190",
    tmdb_rating: 7.6,
    douban_rating: 7.7,
  },
  {
    tmdb_id: 2000069,
    media_type: "movie",
    title: "爆裂鼓手",
    original_title: "Whiplash",
    year: 2014,
    poster_path: null,
    overview: "年轻鼓手在魔鬼导师的摧折下，以近乎自毁的执着追逐极致的完美。",
    director: "达米恩·查泽雷",
    writer: "达米恩·查泽雷",
    cast: "迈尔斯·特勒 / J·K·西蒙斯 / 保罗·雷瑟",
    genres: "剧情 / 音乐",
    country: "美国",
    language: "英语",
    release_date: "2015-02-06(中国大陆)",
    runtime: 107,
    aka: "鼓动真我 / 进击的鼓手",
    imdb_id: "tt2582802",
    tmdb_rating: 8.3,
    douban_rating: 8.4,
  },
  {
    tmdb_id: 2000070,
    media_type: "movie",
    title: "爱乐之城",
    original_title: "La La Land",
    year: 2016,
    poster_path: null,
    overview: "怀揣演员梦的米娅与爵士钢琴师塞巴斯蒂安在洛杉矶相爱，却在理想与现实间分岔。",
    director: "达米恩·查泽雷",
    writer: "达米恩·查泽雷",
    cast: "瑞恩·高斯林 / 艾玛·斯通 / 约翰·传奇",
    genres: "剧情 / 爱情 / 音乐",
    country: "美国",
    language: "英语",
    release_date: "2016-12-09(中国大陆)",
    runtime: 128,
    aka: "星声梦里人 / 乐来越爱你",
    imdb_id: "tt3783958",
    tmdb_rating: 7.9,
    douban_rating: 7.8,
  },
  {
    tmdb_id: 2000071,
    media_type: "movie",
    title: "血战钢锯岭",
    original_title: "Hacksaw Ridge",
    year: 2016,
    poster_path: null,
    overview: "拒拿武器的军医多斯，在冲绳钢锯岭上赤手救下七十五名战友。",
    director: "梅尔·吉布森",
    writer: "安德鲁·加菲尔德 / 罗伯特·申坎",
    cast: "安德鲁·加菲尔德 / 萨姆·沃辛顿 / 文斯·沃恩",
    genres: "剧情 / 历史 / 战争",
    country: "美国 / 澳大利亚",
    language: "英语",
    release_date: "2016-12-08(中国大陆)",
    runtime: 139,
    aka: "钢锯岭 / 血战钢锯岭（Hacksaw Ridge）",
    imdb_id: "tt2119532",
    tmdb_rating: 8.1,
    douban_rating: 8.2,
  },
  {
    tmdb_id: 2000072,
    media_type: "movie",
    title: "敦刻尔克",
    original_title: "Dunkirk",
    year: 2017,
    poster_path: null,
    overview: "二战初期，四十万盟军被围困海滩，海陆空三线交织成一场沉默的生死撤退。",
    director: "克里斯托弗·诺兰",
    writer: "克里斯托弗·诺兰",
    cast: "菲恩·怀特海德 / 汤姆·格林-卡尼 / 马克·里朗斯",
    genres: "剧情 / 历史 / 战争",
    country: "英国 / 法国 / 美国 / 荷兰",
    language: "英语 / 法语 / 德语",
    release_date: "2017-09-01(中国大陆)",
    runtime: 107,
    aka: "敦刻尔克大撤退",
    imdb_id: "tt5013056",
    tmdb_rating: 7.4,
    douban_rating: 7.7,
  },
  {
    tmdb_id: 2000073,
    media_type: "movie",
    title: "信条",
    original_title: "Tenet",
    year: 2020,
    poster_path: null,
    overview: "特工卷入逆转时间的军备竞赛，在熵减的世界里阻止第三次世界大战。",
    director: "克里斯托弗·诺兰",
    writer: "克里斯托弗·诺兰",
    cast: "约翰·大卫·华盛顿 / 罗伯特·帕丁森 / 伊丽莎白·德比茨基",
    genres: "动作 / 科幻 / 悬疑",
    country: "英国 / 美国",
    language: "英语 / 乌克兰语 / 俄语 / 爱沙尼亚语",
    release_date: "2020-09-04(中国大陆)",
    runtime: 150,
    aka: "天能 / TENET",
    imdb_id: "tt6723592",
    tmdb_rating: 7.3,
    douban_rating: 7.3,
  },
  {
    tmdb_id: 2000074,
    media_type: "movie",
    title: "1917",
    original_title: "1917",
    year: 2019,
    poster_path: null,
    overview: "一战尾声，两名英国士兵穿越敌区传递停止进攻的急令，拯救上千战友。",
    director: "萨姆·门德斯",
    writer: "萨姆·门德斯 / 克里斯蒂·威尔逊-凯恩斯",
    cast: "乔治·麦凯 / 迪恩-查尔斯·查普曼 / 本尼迪克特·康伯巴奇",
    genres: "剧情 / 战争",
    country: "英国 / 美国 / 加拿大",
    language: "英语 / 法语 / 德语",
    release_date: "2020-08-07(中国大陆)",
    runtime: 119,
    aka: "1917：逆战救兵",
    imdb_id: "tt8579674",
    tmdb_rating: 7.8,
    douban_rating: 7.6,
  },
  {
    tmdb_id: 2000075,
    media_type: "movie",
    title: "小丑",
    original_title: "Joker",
    year: 2019,
    poster_path: null,
    overview: "失意喜剧演员亚瑟在社会的冷暴力中坠入癫狂，成为混乱象征的小丑。",
    director: "托德·菲利普斯",
    writer: "托德·菲利普斯 / 斯科特·西尔弗",
    cast: "华金·菲尼克斯 / 罗伯特·德尼罗 / 莎姬·贝兹",
    genres: "剧情 / 犯罪 / 惊悚",
    country: "美国 / 加拿大",
    language: "英语",
    release_date: "2019-10-04(中国大陆)",
    runtime: 122,
    aka: "小丑（Joker）",
    imdb_id: "tt7286456",
    tmdb_rating: 8.2,
    douban_rating: 8.6,
  },
  {
    tmdb_id: 2000076,
    media_type: "movie",
    title: "玩具总动员",
    original_title: "Toy Story",
    year: 1995,
    poster_path: null,
    overview: "牛仔玩偶胡迪与太空人巴斯光年从争宠到并肩，守护小男孩安迪的童年。",
    director: "约翰·拉塞特",
    writer: "约翰·拉塞特 / 彼特·多克特 / 安德鲁·斯坦顿",
    cast: "汤姆·汉克斯 / 蒂姆·艾伦",
    genres: "动画 / 喜剧 / 冒险",
    country: "美国",
    language: "英语",
    release_date: "1995-11-22(美国)",
    runtime: 81,
    aka: "反斗奇兵",
    imdb_id: "tt0114709",
    tmdb_rating: 8.0,
    douban_rating: 7.8,
  },
  {
    tmdb_id: 2000077,
    media_type: "movie",
    title: "狮子王",
    original_title: "The Lion King",
    year: 1994,
    poster_path: null,
    overview: "小狮子辛巴在父亲木法沙罹难后流亡，最终归来夺回荣耀石的王座。",
    director: "罗杰·阿勒斯 / 罗伯·明可夫",
    writer: "艾琳·梅琪 / 乔纳森·罗伯特",
    cast: "马修·布罗德里克 / 杰瑞米·艾恩斯",
    genres: "动画 / 歌舞 / 冒险",
    country: "美国",
    language: "英语",
    release_date: "1994-06-24(美国)",
    runtime: 89,
    aka: "狮子王（The Lion King）",
    imdb_id: "tt0110357",
    tmdb_rating: 8.2,
    douban_rating: 8.6,
  },
  {
    tmdb_id: 2000078,
    media_type: "movie",
    title: "大话西游之月光宝盒",
    original_title: "西遊記第壹佰零壹回之月光寶盒",
    year: 1995,
    poster_path: null,
    overview: "至尊宝为救白晶晶动用月光宝盒穿越时空，却意外牵出与紫霞仙子的宿命。",
    director: "刘镇伟",
    writer: "刘镇伟 / 吴承恩",
    cast: "周星驰 / 莫文蔚 / 蓝洁瑛 / 吴孟达",
    genres: "喜剧 / 爱情 / 奇幻",
    country: "香港",
    language: "粤语",
    release_date: "1995-01-21(香港)",
    runtime: 87,
    aka: "大话西游1",
    imdb_id: "tt0118937",
    tmdb_rating: 7.5,
    douban_rating: 7.5,
  },
  {
    tmdb_id: 2000079,
    media_type: "movie",
    title: "喜剧之王",
    original_title: "喜劇之王",
    year: 1999,
    poster_path: null,
    overview: "跑龙套的尹天仇执着于演员梦，与舞女柳飘飘在底层烟火里相濡以沫。",
    director: "周星驰 / 李力持",
    writer: "周星驰 / 李敏 / 曾瑾昌",
    cast: "周星驰 / 张柏芝 / 莫文蔚",
    genres: "剧情 / 喜剧 / 爱情",
    country: "香港",
    language: "粤语 / 汉语普通话",
    release_date: "1999-02-13(香港)",
    runtime: 85,
    aka: "喜剧之王（The King of Comedy）",
    imdb_id: "tt0213376",
    tmdb_rating: 7.2,
    douban_rating: 7.3,
  },
  {
    tmdb_id: 2000080,
    media_type: "movie",
    title: "唐伯虎点秋香",
    original_title: "唐伯虎點秋香",
    year: 1993,
    poster_path: null,
    overview: "才子唐伯虎为追求佳人秋香混入华府，笑料百出终成眷属。",
    director: "李力持",
    writer: "李力持 / 周星驰 / 谷德昭",
    cast: "周星驰 / 巩俐 / 陈百祥",
    genres: "喜剧 / 爱情 / 古装",
    country: "香港",
    language: "粤语 / 汉语普通话",
    release_date: "1993-07-01(香港)",
    runtime: 102,
    aka: "唐伯虎点秋香（Flirting Scholar）",
    imdb_id: "tt0106686",
    tmdb_rating: 7.0,
    douban_rating: 7.3,
  },
  {
    tmdb_id: 2000081,
    media_type: "movie",
    title: "功夫",
    original_title: "功夫",
    year: 2004,
    poster_path: null,
    overview: "混混阿星误入猪笼城寨，在黑白两道与武林高手的混战中觉醒一身绝学。",
    director: "周星驰",
    writer: "周星驰 / 曾谨昌 / 霍昕",
    cast: "周星驰 / 黄圣依 / 元华 / 元秋",
    genres: "动作 / 喜剧 / 犯罪",
    country: "香港 / 中国大陆",
    language: "粤语 / 汉语普通话",
    release_date: "2004-12-23(中国大陆)",
    runtime: 100,
    aka: "功夫（Kung Fu Hustle）",
    imdb_id: "tt0373074",
    tmdb_rating: 7.4,
    douban_rating: 7.3,
  },
  {
    tmdb_id: 2000082,
    media_type: "movie",
    title: "少林足球",
    original_title: "少林足球",
    year: 2001,
    poster_path: null,
    overview: "落魄的少林武僧以功夫足球挑战黑幕联赛，点燃一群草根兄弟的梦想。",
    director: "周星驰",
    writer: "周星驰 / 曾谨昌",
    cast: "周星驰 / 赵薇 / 吴孟达 / 谢贤",
    genres: "喜剧 / 动作 / 运动",
    country: "香港",
    language: "粤语 / 汉语普通话",
    release_date: "2001-07-12(香港)",
    runtime: 113,
    aka: "少林足球（Shaolin Soccer）",
    imdb_id: "tt0278046",
    tmdb_rating: 6.9,
    douban_rating: 6.9,
  },
  {
    tmdb_id: 2000083,
    media_type: "movie",
    title: "长江七号",
    original_title: "長江7號",
    year: 2008,
    poster_path: null,
    overview: "穷困父亲为儿子买来一只外星小狗七仔，在贫寒中演绎温暖的亲情童话。",
    director: "周星驰",
    writer: "周星驰",
    cast: "周星驰 / 徐娇 / 张雨绮",
    genres: "喜剧 / 科幻 / 家庭",
    country: "香港 / 中国大陆",
    language: "粤语 / 汉语普通话",
    release_date: "2008-01-30(中国大陆)",
    runtime: 103,
    aka: "长江七号（CJ7）",
    imdb_id: "tt0883418",
    tmdb_rating: 6.4,
    douban_rating: 5.9,
  },
  {
    tmdb_id: 2000084,
    media_type: "movie",
    title: "西游伏妖篇",
    original_title: "西遊伏妖篇",
    year: 2017,
    poster_path: null,
    overview: "唐僧师徒西行取经，在降妖除魔的旅途中彼此磨合、笑泪交织。",
    director: "徐克",
    writer: "周星驰 / 今何在与",
    cast: "吴亦凡 / 林允 / 姚晨 / 林更新",
    genres: "喜剧 / 奇幻 / 古装",
    country: "中国大陆 / 香港",
    language: "汉语普通话",
    release_date: "2017-01-28(中国大陆)",
    runtime: 108,
    aka: "西游2",
    imdb_id: "tt5706000",
    tmdb_rating: 5.3,
    douban_rating: 5.3,
  },
  {
    tmdb_id: 2000085,
    media_type: "movie",
    title: "美人鱼",
    original_title: "美人鱼",
    year: 2016,
    poster_path: null,
    overview: "地产大亨刘轩为填海项目接近人鱼珊珊，却在利益与真情间幡然醒悟。",
    director: "周星驰",
    writer: "周星驰 / 李思臻 / 何妙祺",
    cast: "邓超 / 林允 / 罗志祥 / 张雨绮",
    genres: "喜剧 / 爱情 / 科幻 / 奇幻",
    country: "中国大陆 / 香港",
    language: "汉语普通话",
    release_date: "2016-02-08(中国大陆)",
    runtime: 94,
    aka: "美人鱼（The Mermaid）",
    imdb_id: "tt4701660",
    tmdb_rating: 5.9,
    douban_rating: 6.3,
  },
  {
    tmdb_id: 2000086,
    media_type: "movie",
    title: "西游记之大圣归来",
    original_title: "西游记之大圣归来",
    year: 2015,
    poster_path: null,
    overview: "被封印的齐天大圣与孤儿江流儿结伴，一路降妖找回失落的英雄之心。",
    director: "田晓鹏",
    writer: "田晓鹏 / 刘虎 / 米粒",
    cast: "张磊 / 林子杰 / 吴文伦",
    genres: "动画 / 冒险",
    country: "中国大陆",
    language: "汉语普通话",
    release_date: "2015-07-10(中国大陆)",
    runtime: 89,
    aka: "大圣归来",
    imdb_id: "tt4701661",
    tmdb_rating: 6.9,
    douban_rating: 6.9,
  },
  {
    tmdb_id: 2000087,
    media_type: "movie",
    title: "哪吒之魔童降世",
    original_title: "哪吒之魔童降世",
    year: 2019,
    poster_path: null,
    overview: "生而为魔的哪吒不甘天命，以一句「我命由我不由天」逆天改命。",
    director: "饺子",
    writer: "饺子 / 易巧 / 魏芸芸",
    cast: "吕艳婷 / 囧森瑟夫 / 瀚墨",
    genres: "动画 / 奇幻 / 冒险",
    country: "中国大陆",
    language: "汉语普通话",
    release_date: "2019-07-26(中国大陆)",
    runtime: 110,
    aka: "哪吒",
    imdb_id: "tt10243136",
    tmdb_rating: 7.0,
    douban_rating: 7.0,
  },
  {
    tmdb_id: 2000088,
    media_type: "movie",
    title: "流浪地球",
    original_title: "流浪地球",
    year: 2019,
    poster_path: null,
    overview: "太阳将毁灭，人类推动地球逃离太阳系，在木星危机中点燃最后的希望。",
    director: "郭帆",
    writer: "龚格尔 / 严东旭 / 郭帆",
    cast: "屈楚萧 / 吴京 / 李光洁 / 吴孟达",
    genres: "科幻 / 冒险 / 灾难",
    country: "中国大陆",
    language: "汉语普通话 / 俄语 / 英语 / 法语",
    release_date: "2019-02-05(中国大陆)",
    runtime: 125,
    aka: "流浪地球（The Wandering Earth）",
    imdb_id: "tt7605074",
    tmdb_rating: 6.3,
    douban_rating: 6.0,
  },
  {
    tmdb_id: 2000089,
    media_type: "movie",
    title: "流浪地球2",
    original_title: "流浪地球2",
    year: 2023,
    poster_path: null,
    overview: "在移山计划启动前，人类面对数字生命与末日抉择，铺垫一场跨越时空的救援。",
    director: "郭帆",
    writer: "龚格尔 / 郭帆 / 叶濡畅",
    cast: "吴京 / 刘德华 / 李雪健 / 沙溢",
    genres: "科幻 / 冒险 / 灾难",
    country: "中国大陆",
    language: "汉语普通话 / 英语 / 俄语",
    release_date: "2023-01-22(中国大陆)",
    runtime: 173,
    aka: "流浪地球II",
    imdb_id: "tt13556448",
    tmdb_rating: 7.0,
    douban_rating: 6.5,
  },
  {
    tmdb_id: 2000090,
    media_type: "movie",
    title: "疯狂的石头",
    original_title: "疯狂的石头",
    year: 2006,
    poster_path: null,
    overview: "重庆一间工厂的稀世翡翠，引来笨贼、模特与国际大盗的连环爆笑争夺。",
    director: "宁浩",
    writer: "宁浩 / 张承 / 岳小军",
    cast: "郭涛 / 刘桦 / 黄渤 / 徐峥",
    genres: "喜剧 / 犯罪",
    country: "中国大陆",
    language: "汉语普通话 / 重庆话 / 青岛话",
    release_date: "2006-06-30(中国大陆)",
    runtime: 106,
    aka: "疯狂的石头（Crazy Stone）",
    imdb_id: "tt0888557",
    tmdb_rating: 7.1,
    douban_rating: 7.5,
  },
  {
    tmdb_id: 2000091,
    media_type: "movie",
    title: "疯狂的赛车",
    original_title: "疯狂的赛车",
    year: 2009,
    poster_path: null,
    overview: "落魄赛车手因误会卷入毒品交易，与各路人马阴差阳错地纠缠成一团乱麻。",
    director: "宁浩",
    writer: "宁浩 / 王红卫 / 苑琳琳",
    cast: "黄渤 / 戎祥 / 九孔",
    genres: "喜剧 / 犯罪",
    country: "中国大陆",
    language: "汉语普通话 / 闽南语 / 青岛话",
    release_date: "2009-01-20(中国大陆)",
    runtime: 105,
    aka: "疯狂的赛车（The Crazy Racer）",
    imdb_id: "tt1431043",
    tmdb_rating: 6.8,
    douban_rating: 6.4,
  },
  {
    tmdb_id: 2000092,
    media_type: "movie",
    title: "心花路放",
    original_title: "心花路放",
    year: 2014,
    poster_path: null,
    overview: "离婚后的耿浩在兄弟郝义陪同下开启猎艳公路之旅，却在荒诞中疗愈情伤。",
    director: "宁浩",
    writer: "邢爱娜 / 宁浩 / 王元",
    cast: "黄渤 / 徐峥 / 袁泉 / 周冬雨",
    genres: "剧情 / 喜剧 / 爱情",
    country: "中国大陆",
    language: "汉语普通话",
    release_date: "2014-09-30(中国大陆)",
    runtime: 134,
    aka: "心花路放（The Breakup Guru）",
    imdb_id: "tt3803026",
    tmdb_rating: 6.1,
    douban_rating: 5.8,
  },
  {
    tmdb_id: 2000093,
    media_type: "movie",
    title: "无人区",
    original_title: "无人区",
    year: 2013,
    poster_path: null,
    overview: "律师潘肖穿越西北无人区，在黑车司机、盗猎者之间经历一场野蛮与文明的较量。",
    director: "宁浩",
    writer: "述平 / 邢爱娜 / 崔斯韦",
    cast: "徐峥 / 黄渤 / 余男 / 多布杰",
    genres: "剧情 / 喜剧 / 犯罪",
    country: "中国大陆",
    language: "汉语普通话",
    release_date: "2013-12-03(中国大陆)",
    runtime: 117,
    aka: "无人区（No Man's Land）",
    imdb_id: "tt3428088",
    tmdb_rating: 6.8,
    douban_rating: 7.2,
  },
  {
    tmdb_id: 2000094,
    media_type: "movie",
    title: "一出好戏",
    original_title: "一出好戏",
    year: 2018,
    poster_path: null,
    overview: "公司团建遇海难流落荒岛，一群人在与世隔绝中重建秩序，也暴露人性百态。",
    director: "黄渤",
    writer: "黄渤 / 郭俊立 / 查慕春",
    cast: "黄渤 / 舒淇 / 王宝强 / 张艺兴",
    genres: "剧情 / 喜剧",
    country: "中国大陆",
    language: "汉语普通话",
    release_date: "2018-08-10(中国大陆)",
    runtime: 134,
    aka: "一出好戏（The Island）",
    imdb_id: "tt7764958",
    tmdb_rating: 6.1,
    douban_rating: 5.8,
  },
];

// 记录：用脚本统一生成，约 60% 已看（带评分，取豆瓣评分四舍五入）、40% 想看；标签取影片类型。
const records = items.map((it, i) => {
  const watched = i % 5 < 3;
  const rating = watched ? Math.max(1, Math.min(10, Math.round(it.douban_rating ?? 7))) : null;
  return {
    tmdb_id: it.tmdb_id,
    status: (watched ? "watched" : "plan") as "watched" | "plan",
    rating,
    tags: watched ? (it.genres ?? "") : "",
  };
});

async function main() {
  const db = await getDb();
  for (const it of items) {
    await ensureItem(db, it);
  }
  for (const r of records) {
    await upsertRecord(db, { tmdb_id: r.tmdb_id, status: r.status, rating: r.rating, tags: r.tags });
  }
  console.log(`✓ 种子完成：插入 ${items.length} 部影片，${records.length} 条记录。`);
}

main().catch((e) => {
  console.error("种子执行失败：", e);
  process.exit(1);
});
